runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /.*
  script: main.app

libraries:
- name: flask
  version: 0.12